### PR TITLE
BugFix - data length error

### PR DESCRIPTION
**Pull request by Yeraze**
Even tho this is a "LONG" type, it's actually only 4 bytes. Typecasting
it to a long* caused a dereference beyond the end of the allocated
region.

Potential fix for #28 .. @jmallach please review.

### CODE REVIEW

**Comment by jmallach** [comment]
The long -> int change looks reasonable to me, but I don't consider my C knowledge to be too good to actually act as a reviewer ;) 

What I do notice is the lack of warning reporting in general. You should use -Wall at the very least. In Debian I actually add -Wextra as well and the result is... interesting. Fedora has patches to silence all of these.

**Comment by Yeraze** [comment]
I do that myself regularly as a first-step static analysis (and I run cppcheck regularly).  All I see is some rather harmless 'unused parameters' and 'comparing int & unsigned int' warnings, nothing I consider too harmful.

Are you seeing something more serious?

**Comment by jmallach** [comment]
Finally, these two new issues could probably get additional CVE numbers. I requested the others for you and can do these two as well, but you can do it using the mitre web form at https://cveform.mitre.org/

**Comment by jmallach** [comment]
Re: warnings, no. It's just I'm unused to seeing a project not using at least -Wall. I'm unsure if any of them are actually potentially dangerous or can cause problems.

**Pull request merged**
