### PR TITLE
resolves #77: attachment size limit too small

### LINKED ISSUE #77: ERROR: invalid alloc size 1258056 at ytnef.c : 1183, suspected corruption (exceeded 1000000 bytes)
This limit is too small; the attachment really is over 1MB in size.

### PR DESCRIPTION
**Pull request by ohwgiles**

### CODE REVIEW

**Comment by ohwgiles** [comment]
There are several such limits, and I think exposing them all would be overkill. Given the verbosity of the error message, I think finding and changing the limit is not significantly more difficult than modifying a compile time option, for users who are so inclined. Just my 2c.

Btw maybe the limit should just be increased? It’s not hard and fast, just a soft trade off between convenience and risk of memory exhaustion attacks - all these limits were introduced in response to CVEs, if you’re interested you should find the details in the git history

**Comment by Yeraze** [comment]
Does anyone have an email client that allows 500MB attachments?  I thought most of them stopped around 20-50MB.

**Comment by wwp** [comment]
I'm afraid that by the facts, attachments' max size in emails is not really about the MUAs but the MTAs or the mail servers themselves.
[](https://en.wikipedia.org/wiki/Email_attachment)

**Comment by Yeraze** [comment]
client, server..t he line gets so fuzzy these days with all the web providers.  I was looking at this : https://www.outlook-apps.com/maximum-email-size/ ... I get for custom MTA's people can set whatever limits they want, but if they can configure sendmail they can probably recompile ytnef :)

That said, take a look at #79 where I added a commandline argument & struct parameter for the maximum attachment size in MB.

**Comment by Yeraze** [comment]
Resolved via #79

**Pull request closed without merging**
